# Generated by Django 3.2.3 on 2021-11-02 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudarat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sudarat_tb_model',
            old_name='member_detail',
            new_name='detail_news',
        ),
        migrations.RenameField(
            model_name='sudarat_tb_model',
            old_name='member_image',
            new_name='photo_news',
        ),
        migrations.RemoveField(
            model_name='sudarat_tb_model',
            name='member_firstname',
        ),
        migrations.RemoveField(
            model_name='sudarat_tb_model',
            name='member_lastname',
        ),
        migrations.RemoveField(
            model_name='sudarat_tb_model',
            name='member_studentId',
        ),
        migrations.AddField(
            model_name='sudarat_tb_model',
            name='date_news',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sudarat_tb_model',
            name='toppic_news',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
