# Generated by Django 3.2.3 on 2021-11-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudarat_app', '0002_auto_20211102_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sudarat_tb_model',
            name='date_news',
        ),
    ]
