# Generated by Django 3.2.3 on 2021-11-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudarat_app', '0004_sudarat_tb_model_date_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sudarat_tb_model',
            old_name='detail_news',
            new_name='member_detail',
        ),
        migrations.RenameField(
            model_name='sudarat_tb_model',
            old_name='photo_news',
            new_name='member_image',
        ),
        migrations.RemoveField(
            model_name='sudarat_tb_model',
            name='date_news',
        ),
        migrations.RemoveField(
            model_name='sudarat_tb_model',
            name='toppic_news',
        ),
        migrations.AddField(
            model_name='sudarat_tb_model',
            name='member_firstname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sudarat_tb_model',
            name='member_lastname',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sudarat_tb_model',
            name='member_studentId',
            field=models.CharField(default='exit', max_length=200),
            preserve_default=False,
        ),
    ]
